// <auto-generated />
using FutureBankingDashboard.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutureBankingDashboard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827124825_SeedDataUpdate")]
    partial class SeedDataUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FutureBankingDashboard.Library.Models.EconomyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Expenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Economy", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 40000m,
                            CompanyId = 1,
                            Expenses = 80000m,
                            Income = 120000m
                        },
                        new
                        {
                            Id = 2,
                            Balance = 45000m,
                            CompanyId = 1,
                            Expenses = 85000m,
                            Income = 130000m
                        },
                        new
                        {
                            Id = 3,
                            Balance = 43000m,
                            CompanyId = 1,
                            Expenses = 82000m,
                            Income = 125000m
                        },
                        new
                        {
                            Id = 4,
                            Balance = 50000m,
                            CompanyId = 1,
                            Expenses = 90000m,
                            Income = 140000m
                        },
                        new
                        {
                            Id = 5,
                            Balance = 55000m,
                            CompanyId = 1,
                            Expenses = 95000m,
                            Income = 150000m
                        });
                });

            modelBuilder.Entity("FutureBankingDashboard.Library.Models.FundingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredCo2Score")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Funding", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUrl = "https://example.com/omstillingspulje",
                            Description = "Støtte til virksomheder der reducerer CO2‑udledning.",
                            RequiredCo2Score = "C",
                            Title = "Grøn Omstillingspulje"
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUrl = "https://example.com/energi",
                            Description = "Tilskud til energieffektive løsninger.",
                            RequiredCo2Score = "B",
                            Title = "Energiforbedringsstøtte"
                        },
                        new
                        {
                            Id = 3,
                            ApplicationUrl = "https://example.com/digital",
                            Description = "Funding til digitale grønne projekter.",
                            RequiredCo2Score = "B",
                            Title = "Digital Grøn Innovation"
                        },
                        new
                        {
                            Id = 4,
                            ApplicationUrl = "https://example.com/smv",
                            Description = "Støtte til små og mellemstore virksomheder.",
                            RequiredCo2Score = "D",
                            Title = "SMV Grøn"
                        },
                        new
                        {
                            Id = 5,
                            ApplicationUrl = "https://example.com/eu",
                            Description = "EU‑tilskud til klimaprojekter.",
                            RequiredCo2Score = "A",
                            Title = "EU KlimaFond"
                        });
                });

            modelBuilder.Entity("FutureBankingDashboard.Library.Models.RecommendationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recommendations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Priority = 1,
                            Text = "Reducer energiforbruget i produktionen."
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Priority = 2,
                            Text = "Skift til grønne leverandører."
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            Priority = 3,
                            Text = "Invester i solceller."
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 1,
                            Priority = 2,
                            Text = "Optimer transportlogistik."
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 1,
                            Priority = 1,
                            Text = "Implementér CO2‑overvågning."
                        });
                });

            modelBuilder.Entity("FutureBankingDashboard.Library.Models.SustainabilityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Co2Score")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("GreenEnergiPercentage")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyEmission")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sustainability", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Co2Score = "D",
                            CompanyId = 1,
                            GreenEnergiPercentage = 35,
                            MonthlyEmission = 1400m
                        },
                        new
                        {
                            Id = 2,
                            Co2Score = "C",
                            CompanyId = 1,
                            GreenEnergiPercentage = 38,
                            MonthlyEmission = 1350m
                        },
                        new
                        {
                            Id = 3,
                            Co2Score = "C",
                            CompanyId = 1,
                            GreenEnergiPercentage = 40,
                            MonthlyEmission = 1300m
                        },
                        new
                        {
                            Id = 4,
                            Co2Score = "B",
                            CompanyId = 1,
                            GreenEnergiPercentage = 43,
                            MonthlyEmission = 1250m
                        },
                        new
                        {
                            Id = 5,
                            Co2Score = "B",
                            CompanyId = 1,
                            GreenEnergiPercentage = 45,
                            MonthlyEmission = 1200m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
